[package]
name = "vpn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
etherparse = "0.13"
libc = "0.2"
socket2 = { version = "0.5.7", features = ["all"], optional = true }
thiserror = "1.0.60"
