[package]
name = "tunnel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
etherparse = "0.14.3"
libc = "0.2.155"
ring = "0.17.8"
socket2 = "0.5.7"
thiserror = "1.0.61"
